### ISSUE TITLE
What's the font in previews?

### ISSUE THREAD

**Issue by cigneve** [woosaaahh/sj.nvim#21]

**Comment by woosaaahh** [comment]
I use a custom version of [Iosevka](https://github.com/be5invis/Iosevka).

Here is the config file to [build](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md) this font : 

`private-build-plans.toml`
```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
no-ligation = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom.variants.design]
    a = "double-storey-serifless"
    b = "toothless-corner"
    d = "toothless-corner-serifless"
    e = "rounded"
    g = "single-storey-earless-corner-flat-hook"
    i = "tailed-serifed"
    k = "straight-serifless"
    l = "tailed-serifed"
    p = "earless-corner"
    q = "earless-corner"
    r = "compact"
    u = "toothless-corner"
    v = "curly"
    w = "curly"
    x = "curly-serifless"
    y = "curly-turn"
    z = "curly-serifless"
    zero = "slashed"
    four = "semi-open"
    six = "open-contour"
    eight = "crossing-asymmetric"
    nine = "open-contour"
    ampersand = "upper-open"
    at = "fourfold-solid-inner-tall"
    bar = "force-upright"
    brace = "curly-flat-boundary"
    dollar = "open"
    number-sign = "slanted-tall"
    question = "smooth"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"
```
